branches:
  only:
  - ci_support

environment:
  matrix:
  - BUILD_SYSTEM: bazel

install:
- IF "%BUILD_SYSTEM%"=="bazel" (
    appveyor DownloadFile https://github.com/bazelbuild/bazel/releases/download/0.6.1/bazel-0.6.1-windows-x86_64.exe -FileName bazel.exe
  )

build_script:
- IF "%BUILD_SYSTEM%"=="bazel" (
    cd plugin
    bazel build :protoc-gen-zcharp
  )